### ISSUE TITLE
Sveltekit Vite error: SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by btakita** [fgnass/spin.js#384]
Looks like we need an ESM output for this to work.

1:45:21 AM [vite] Error when evaluating SSR module /@fs/home/user/work/project/libs/ladda/src/ladda.js:
/home/home/user/work/project/node_modules/.pnpm/spin.js@4.1.0/node_modules/spin.js/spin.js:82
export { Spinner };
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:353:18)
    at wrapSafe (node:internal/modules/cjs/loader:1039:15)
    at Module._compile (node:internal/modules/cjs/loader:1073:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at nodeRequire (/home/brian/work/menus/menus-angular-2-app/node_modules/.pnpm/vite@2.4.2/node_modules/vite/dist/node/chunks/dep-11db14da.js:73337:17)
    at ssrImport (/home/brian/work/menus/menus-angular-2-app/node_modules/.pnpm/vite@2.4.2/node_modules/vite/dist/node/chunks/dep-11db14da.js:73290:20)
Unexpected token 'export'

**Comment by theodorejb** [comment]
If SvelteKit / Vite doesn't support ES modules, that sounds like a bug in Vite that should be reported there.
